# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Parse-Snort
version:      0.01
version_from: lib/Parse/Snort.pm
installdirs:  site
requires:
    Carp:                          0
    Class::Accessor:               0
    List::Util:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
